services:
  frontend:
    container_name: ticker-frontend
    restart: unless-stopped
    build: .
    ports:
      - '8080:80'
    environment:
      # Must include the /v1 suffix.
      TICKER_API_URL: ${TICKER_API_URL:-http://host.docker.internal:8080/v1}
