name: Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ['12', '14', '16']

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Set up Node (${{ matrix.node-version }})
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
