name: Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn run test --coverage

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-20.04
    needs: [test]
    strategy:
      matrix:
        node-version: ["16", "18", "current"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node (${{ matrix.node-version }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run build

  automerge:
    name: Merge Automatically
    needs: [test, build]
    runs-on: ubuntu-20.04

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Obtain Access Token
        id: acces_token
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.SYSTEMLI_APP_CREDENTIALS_TOKEN }})"
          echo "::add-mask::$TOKEN"
          echo "::set-output name=token::$TOKEN"

      - name: Merge
        uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ steps.acces_token.outputs.token }}
