name: Quality

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Prettier
        uses: wearerequired/lint-action@v2
        with:
          check_name: Prettier Results
          prettier: true
          prettier_dir: src

  eslint:
    name: ESLint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        uses: wearerequired/lint-action@v2
        with:
          check_name: ESLint Results
          eslint: true
          eslint_extensions: ts,tsx,js,jsx
          eslint_dir: src
